/**********************************************************************************************************************
 * \file GTM_TOM_PWM.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Motor_driver.h"
#include "Control_section/Motor_control.h"
#include "Sensor_Input/Encoder.h"
#include "Ifx_Types.h"
#include "IfxGtm_Tom_Pwm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_TOM    20                                      /* Interrupt priority number                    */
//#define LED                 IfxGtm_TOM0_1_TOUT103_P10_1_OUT         /* LED which will be driven by the PWM          */
//#define BUZZER              IfxGtm_TOM1_11_TOUT3_P02_3_OUT

#define MOTOR_B             IfxGtm_TOM0_3_TOUT105_P10_3_OUT
#define MOTOR_A             IfxGtm_TOM0_9_TOUT1_P02_1_OUT

#define DIR_A       &MODULE_P10,1
#define PWM_A       &MODULE_P02,1
#define BREAK_A     &MODULE_P02,7

#define DIR_B       &MODULE_P10,2
#define PWM_B       &MODULE_P10,3
#define BREAK_B     &MODULE_P02,6

#define PWM_PERIOD          50000                                   /* PWM period for the TOM                       */
#define FADE_STEP           PWM_PERIOD / 100                        /* PWM duty cycle for the TOM                   */


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxGtm_Tom_Pwm_Config g_tomConfigA;                                  /* Timer configuration structure                */
IfxGtm_Tom_Pwm_Driver g_tomDriverA;                                  /* Timer Driver structure                       */
IfxGtm_Tom_Pwm_Config g_tomConfigB;                                  /* Timer configuration structure                */
IfxGtm_Tom_Pwm_Driver g_tomDriverB;                                  /* Timer Driver structure                       */
uint32 g_fadeValue = 0;                                             /* Fade value, starting from 0                  */
uint32 adcResult = 0;
sint8 g_fadeDir = 1;                                                /* Fade direction variable                      */

float32 error_vel_left;
float32 error_vel_right;

uint32 error_vel_int_left, error_vel_int_old_left;
uint32 error_vel_int_right, error_vel_int_old_right;

float32 Vin_left;
float32 Vin_right;


float32 kp = 1, ki = 4;

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/
/* This function initializes the TOM */
void Init_DCMotors(void)
{
    /* Init CH-A (Left Motor) */
    IfxPort_setPinModeOutput(DIR_A, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);    /* DIR-A 출력 핀 설정 */
//    IfxPort_setPinModeOutput(PWM_A, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);    /* PWM-A 출력 핀 설정 */
//    IfxPort_setPinModeOutput(BREAK_A, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);  /* BRAKE-A 출력 핀 설정 */
    IfxPort_setPinHigh(DIR_A);      /* 모터 회전 방향 (1: 앞, 0: 뒤) */
//    IfxPort_setPinHigh(BREAK_A);    /* 모터 정지 (1: 정지, 0: PWM-A에 따라 동작) */
//    IfxPort_setPinLow(PWM_A);      /* 100% PWM duty  */

    /* Init CH-B (Right Motor) */
    IfxPort_setPinModeOutput(DIR_B, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);    /* DIR-B 출력 핀 설정 */
//    IfxPort_setPinModeOutput(PWM_B, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);    /* PWM-B 출력 핀 설정 */
//    IfxPort_setPinModeOutput(BREAK_B, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);  /* BRAKE-B 출력 핀 설정 */
//    IfxPort_setPinHigh(DIR_B);      /* 모터 회전 방향 (1: 앞, 0: 뒤) */
//    IfxPort_setPinHigh(BREAK_B);    /* 모터 정지 (1: 정지, 0: PWM-B에 따라 동작) */
//    IfxPort_setPinLow(PWM_B);      /* 100% PWM duty  */
}

void movChA(int dir)
{
    if(dir)
    {
        IfxPort_setPinHigh(DIR_A); /* 모터 회전 방향 (1: 앞, 0: 뒤) */
    }
    else {
        IfxPort_setPinLow(DIR_A); /* 모터 회전 방향 (1: 앞, 0: 뒤) */
    }
    IfxPort_setPinLow(BREAK_A); /* 모터 정지 (1: 정지, 0: PWM-A에 따라 동작) */
    IfxPort_setPinHigh(PWM_A); /* 100% PWM duty  */
}

void movChB(int dir)
{
    if(dir)
    {
        IfxPort_setPinHigh(DIR_B); /* 모터 회전 방향 (1: 앞, 0: 뒤) */
    }
    else {
        IfxPort_setPinLow(DIR_B); /* 모터 회전 방향 (1: 앞, 0: 뒤) */
    }
    IfxPort_setPinLow(BREAK_B); /* 모터 정지 (1: 정지, 0: PWM-B에 따라 동작) */
    IfxPort_setPinHigh(PWM_B); /* 100% PWM duty  */
}


void initGtmTomPwm(void)
{
    IfxGtm_enable(&MODULE_GTM);                                     /* Enable GTM                                   */

    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);   /* Enable the FXU clock                         */

    /* Initialize the configuration structure with default parameters */
    IfxGtm_Tom_Pwm_initConfig(&g_tomConfigA, &MODULE_GTM);

    g_tomConfigA.tom = MOTOR_A.tom;                                      /* Select the TOM depending on the LED          */
    g_tomConfigA.tomChannel = MOTOR_A.channel;                           /* Select the channel depending on the LED      */
    g_tomConfigA.period = PWM_PERIOD;                                /* Set the timer period                         */
    g_tomConfigA.pin.outputPin = &MOTOR_A;                               /* Set the LED port pin as output               */
    g_tomConfigA.synchronousUpdateEnabled = TRUE;                    /* Enable synchronous update                    */

    IfxGtm_Tom_Pwm_init(&g_tomDriverA, &g_tomConfigA);                /* Initialize the GTM TOM                       */
    IfxGtm_Tom_Pwm_start(&g_tomDriverA, TRUE);                       /* Start the PWM                                */

    IfxGtm_Tom_Pwm_initConfig(&g_tomConfigB, &MODULE_GTM);

    g_tomConfigB.tom = MOTOR_B.tom;                                      /* Select the TOM depending on the LED          */
    g_tomConfigB.tomChannel = MOTOR_B.channel;                           /* Select the channel depending on the LED      */
    g_tomConfigB.period = PWM_PERIOD;                                /* Set the timer period                         */
    g_tomConfigB.pin.outputPin = &MOTOR_B;                               /* Set the LED port pin as output               */
    g_tomConfigB.synchronousUpdateEnabled = TRUE;                    /* Enable synchronous update                    */

    IfxGtm_Tom_Pwm_init(&g_tomDriverB, &g_tomConfigB);                /* Initialize the GTM TOM                       */
    IfxGtm_Tom_Pwm_start(&g_tomDriverB, TRUE);                       /* Start the PWM                                */
}


/* This function creates the fade effect for the LED */
//void fadeLED(void)
//{
//    // 24_2_22 PWM PRAC_1
////    adcResult = Driver_Adc0_DataObtain() * 10;
////    Driver_Adc0_ConvStart();
//    if((g_fadeValue + FADE_STEP) >= PWM_PERIOD)
//    {
//        g_fadeDir = -1;                                             /* Set the direction of the fade                */
//    }
//    else if((g_fadeValue - FADE_STEP) <= 0)
//    {
//        g_fadeDir = 1;                                              /* Set the direction of the fade                */
//    }
//    g_fadeValue += g_fadeDir * FADE_STEP;                           /* Calculation of the new duty cycle            */
//    setDutyCycle(g_fadeValue);                                      /* Set the duty cycle of the PWM                */
//}

/* This function sets the duty cycle of the PWM */
void setDutyCycleA(float dutyCycle)
{
    g_tomConfigA.dutyCycle = dutyCycle * 50000;                              /* Change the value of the duty cycle           */
    IfxGtm_Tom_Pwm_init(&g_tomDriverA, &g_tomConfigA);                /* Re-initialize the PWM                        */
}

void setDutyCycleB(float dutyCycle)
{
    g_tomConfigB.dutyCycle = dutyCycle * 50000;                              /* Change the value of the duty cycle           */
    IfxGtm_Tom_Pwm_init(&g_tomDriverB, &g_tomConfigB);                /* Re-initialize the PWM                        */
}

void pid_control_left(void){

    error_vel_left = cur_velo_wheel.v_left - Left_velocity;
    error_vel_int_left = error_vel_int_old_left + (error_vel_left) * 0.001;
    error_vel_int_old_left = error_vel_int_left;

    if(error_vel_int_left > 10)
    {
        error_vel_int_left = 10;
    }
    Vin_left = (kp * error_vel_left + ki * error_vel_int_left);

    if(Vin_left > 11)
    {
        Vin_left = 11;
    }
    else if(Vin_left < 0)
    {
        Vin_left = 0;
    }

    setDutyCycleA(Vin_left);
}

void pid_control_right(void){

    error_vel_right = cur_velo_wheel.v_right - Right_velocity;
    error_vel_int_right = error_vel_int_old_right + (error_vel_right) * 0.001;
    error_vel_int_old_right = error_vel_int_right;

    if(error_vel_int_right > 10)
    {
        error_vel_int_right = 10;
    }
    Vin_right = (kp * error_vel_right + ki * error_vel_int_right);

    if(Vin_right > 11)
    {
        Vin_right = 11;
    }
    else if(Vin_right < 0)
    {
        Vin_right = 0;
    }

    setDutyCycleB(Vin_right);
}
